export const NOW_CARDS = [
  {
    tag: "// shipping",
    title_a: "nexus",
    title_b: " backend",
    body: "designing apis + databases against the nexus EVM. node, rust, gcp.",
    icon: "bolt",
    color: "#a64a3a",
    tape: "top",
  },
  {
    tag: "// reading",
    title_a: "designing data-",
    title_b: "intensive apps",
    body: "designing data-intensive applications — third read. still finding new things.",
    icon: "coffee",
    color: "#3d6e6e",
    tape: "tl",
  },
  {
    tag: "// learning",
    title_a: "more rust,",
    title_b: " less suffering",
    body: "going deeper into rust — lifetimes, async, and systems-level patterns.",
    icon: "diamond",
    color: "#c79b3a",
    tape: "tr",
  },
  {
    tag: "// listening",
    title_a: "boards of canada",
    title_b: " / aphex",
    body: "fits the dithered-monitor vibe. on loop while debugging.",
    icon: "moon",
    color: "#1a1815",
    tape: "top",
  },
  {
    tag: "// missing",
    title_a: "competitive",
    title_b: " programming",
    body: "icpc 2019–2021 south america regional. competitive programming shaped how i think about problems.",
    icon: "star",
    color: "#a64a3a",
    tape: "tl",
  },
  {
    tag: "// side quest",
    title_a: "this site,",
    title_b: " on weekends",
    body: "this site, built on weekends. stickers are draggable.",
    icon: "heart",
    color: "#c79b3a",
    tape: "tr",
  },
]
