export const STACK_ITEMS = [
  {
    num: "// 001",
    title_a: "Rust",
    title_b: "",
    desc: "for systems where correctness and performance are non-negotiable.",
    price: "$$$",
  },
  {
    num: "// 002",
    title_a: "Node",
    title_b: "JS",
    desc: "the lingua franca of \"just ship it.\"",
    price: "$$",
  },
  {
    num: "// 003",
    title_a: "Type",
    title_b: "Script",
    desc: "typed javascript. better contracts, fewer surprises.",
    price: "$$",
  },
  {
    num: "// 004",
    title_a: "Python",
    title_b: "",
    desc: "data pipelines, ml training, two years in pandas and scipy.",
    price: "$$",
  },
  {
    num: "// 005",
    title_a: "C",
    title_b: "++",
    desc: "competitive programming muscle memory.",
    price: "$",
  },
  {
    num: "// 006",
    title_a: "Java",
    title_b: " / Spring",
    desc: "backend services and rest apis for enterprise systems.",
    price: "$",
  },
  {
    num: "// 007",
    title_a: "Postgres",
    title_b: "",
    desc: "still the right answer most of the time.",
    price: "$$$",
  },
  {
    num: "// 008",
    title_a: "Mongo",
    title_b: "DB",
    desc: "occasionally the right answer.",
    price: "$$",
  },
  {
    num: "// 009",
    title_a: "Fire",
    title_b: "store",
    desc: "document database. used for flexible, real-time data models.",
    price: "$$",
  },
  {
    num: "// 010",
    title_a: "GCP",
    title_b: "",
    desc: "bigtable, run, storage, the usual suspects.",
    price: "$$$",
  },
  {
    num: "// 011",
    title_a: "EVM",
    title_b: "",
    desc: "writing humane apis on top of opcodes.",
    price: "$$",
  },
  {
    num: "// 012",
    title_a: "React",
    title_b: "",
    desc: "for when the ui matters. (it always matters.)",
    price: "$$",
  },
  {
    num: "// 013",
    title_a: "Tensor",
    title_b: "Flow",
    desc: "trained CNNs on synthetic satellite data.",
    price: "$$",
  },
  {
    num: "// 014",
    title_a: "Unity",
    title_b: " / C#",
    desc: "generated synthetic satellite datasets for thesis research.",
    price: "$",
  },
  {
    num: "// 015",
    title_a: "GH",
    title_b: " Actions",
    desc: "ci/cd automation for builds, tests, and deploys.",
    price: "$$",
  },
  {
    num: "// 016",
    title_a: "vim",
    title_b: "",
    desc: "primary editor. modal editing, fast navigation.",
    price: "free",
  },
]
