const ENTRIES = [
  {
    when: "apr 2026 → present",
    role: "Backend Engineer",
    at: "Nexus",
    where: "san francisco · remote from córdoba",
    bullets: [
      "designing & implementing backend services + apis (NodeJS, Rust)",
      "data models + persistence on GCP / Firestore",
      "integrating internal systems against the Nexus EVM blockchain",
      "deployment, monitoring, the whole observability dance",
    ],
    stack: ["NodeJS", "Rust", "Firestore", "GCP", "EVM"],
  },
  {
    when: "oct 2023 → mar 2026",
    role: "AI Training / Prompt Engineer",
    at: "Outlier",
    where: "remote",
    bullets: [
      "reviewed + optimized python code generated by llms",
      "designed evaluation prompts to surface model weaknesses",
      "generated training data on debugging, perf, best practices",
      "pandas / matplotlib / scipy / data analysis workflows",
    ],
    stack: ["Python", "pandas", "scipy", "LLMs"],
  },
  {
    when: "oct 2021 → oct 2022",
    role: "Software Engineer",
    at: "Leniolabs",
    where: "santiago, cl · for ICE Mortgage Tech",
    bullets: [
      "built user-facing features for EPPS in React",
      "reusable UI components on top of Material UI",
      "WCAG accessibility compliance work",
      "refactored a lot of legacy frontend into something readable",
      "CI/CD with GitHub Actions + Jenkins",
    ],
    stack: ["React", "Material UI", "GH Actions", "Jenkins"],
  },
  {
    when: "oct 2019 → oct 2021",
    role: "Full-Stack Engineer",
    at: "Zenrise",
    where: "córdoba, ar",
    bullets: [
      "react dashboards + matching backend functionality",
      "REST services in Java Spring Boot",
      "async pipelines for payments + 3rd-party banking integrations",
      "secure apis with node, express, mongo",
      "sql + nosql schema design and query optimization",
    ],
    stack: ["React", "Spring Boot", "Node", "Mongo", "SQL"],
  },
  {
    when: "2017 → 2024",
    role: "B.Sc + M.Sc Computer Science",
    at: "FaMAF, UNC",
    where: "córdoba, argentina · gpa 8.3",
    bullets: [
      "thesis: computer vision methods for satellite pose estimation",
      "synthetic datasets in unity + c#, simulating satellite imagery",
      "trained CNNs in tensorflow, integrated real data from u. de chile",
      "associate teacher of competitive programming (2019)",
    ],
    stack: ["TensorFlow", "Unity / C#", "Python", "C++"],
  },
  {
    when: "2018 → 2021",
    role: "Competitive Programming",
    at: "ACM-ICPC + Torneo Argentino",
    where: "south america regional",
    bullets: [
      "icpc south america regional 2019–2021",
      "torneo argentino de programación 2018–2020",
      "miss it every day. would not do it again.",
    ],
    stack: ["C++", "algorithms", "regret"],
  },
]

export function Experience() {
  return (
    <section className="section exp" id="experience">
      <span className="section-label">/ experience</span>
      <h2>
        <span className="a">where</span>{" "}
        <span className="s">i&apos;ve</span>{" "}
        <span className="p">been</span>{" "}
        <span className="m">·</span>{" "}
        <span className="s">what</span>{" "}
        <span className="a">broke</span>.
      </h2>
      <div className="timeline">
        {ENTRIES.map((e, i) => (
          <div className="entry" key={i}>
            <div className="when">{e.when}</div>
            <div className="role">
              <h3>{e.role}</h3>
              <span className="at">@ {e.at}</span>
            </div>
            <div className="where">{e.where}</div>
            <ul>
              {e.bullets.map((b, j) => <li key={j}>{b}</li>)}
            </ul>
            <div className="stack">
              {e.stack.map((s, j) => <span className="chip" key={j}>{s}</span>)}
            </div>
          </div>
        ))}
      </div>
    </section>
  )
}
